Repository puppetlabs/puppetlabs_spec_helper, pull requests merged in 2022-10, with the labels that each got.

#356 (CONT-236) Workflow updates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/labeller.yml
  .github/workflows/release.yml
  .github/workflows/release_prep.yml
  .travis.yml
Labels: maintenance

#358 (CONT-237) Bump minimum Ruby version requirement
  Gemfile
  puppetlabs_spec_helper.gemspec
Labels: backwards-incompatible

#348 Drop outdated future parser support
  lib/puppetlabs_spec_helper/rake_tasks.rb
Labels: backwards-incompatible

#357 (CONT-237) Rubocop and Rakefile updates
  .rubocop.yml
  .rubocop_todo.yml
  Rakefile
Labels: maintenance

#360 (CONT-237) Rubocop updates
  lib/puppetlabs_spec_helper/module_spec_helper.rb
  lib/puppetlabs_spec_helper/puppet_spec_helper.rb
  lib/puppetlabs_spec_helper/puppetlabs_spec/files.rb
  lib/puppetlabs_spec_helper/puppetlabs_spec/fixtures.rb
  lib/puppetlabs_spec_helper/puppetlabs_spec/matchers.rb
  lib/puppetlabs_spec_helper/puppetlabs_spec/puppet_internals.rb
  lib/puppetlabs_spec_helper/rake_tasks.rb
  lib/puppetlabs_spec_helper/tasks/check_symlinks.rb
  lib/puppetlabs_spec_helper/tasks/fixtures.rb
  spec/acceptance/smoke_spec.rb
  spec/unit/puppetlabs_spec_helper/puppetlabs_spec/puppet_internals_spec.rb
  spec/unit/puppetlabs_spec_helper/tasks/fixtures_spec.rb
  spec/watchr.rb
Labels: bug

#353 Add rspec-github integration
  lib/puppetlabs_spec_helper/module_spec_helper.rb
  puppetlabs_spec_helper.gemspec
Labels: maintenance

#364 (CONT-237) Deprecation and legacy version support removal
  .noexec.yaml
  README.md
  lib/puppetlabs_spec_helper/module_spec_helper.rb
  lib/puppetlabs_spec_helper/puppet_spec_helper.rb
  lib/puppetlabs_spec_helper/puppetlabs_spec/matchers.rb
  lib/puppetlabs_spec_helper/puppetlabs_spec/puppet_internals.rb
  lib/puppetlabs_spec_helper/rake_tasks.rb
  lib/puppetlabs_spec_helper/version.rb
  puppet_spec_helper.rb
  puppetlabs_spec_helper.gemspec
  puppetlabs_spec_helper.rb
  spec/spec_helper.rb
  spec/unit/puppetlabs_spec_helper/puppetlabs_spec/puppet_internals_spec.rb
Labels: backwards-incompatible
