Repository puppetlabs/puppetlabs_spec_helper, pull requests merged in 2023-09, with the labels that each got.

#406 README.md: replace git:// with https://
  README.md
Labels: community

#407 pdksync - (CAT-1132) Add CI codeowners and version badges to README
  README.md
Labels: maintenance

#408 pdksync - (CAT-1132) Fix README badge link
  README.md
Labels: maintenance

#409 (CAT-1430) - Require puppet-lint ~> 4.0
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  puppetlabs_spec_helper.gemspec
Labels: bugfix
