Repository puppetlabs/puppetlabs_spec_helper, pull requests merged in 2023-01, with the labels that each got.

#370 (maint) - add vendor directory to git ignore
  .gitignore
Labels: maintenance

#373 (GH-372) Reset min Ruby requirement
  puppetlabs_spec_helper.gemspec
Labels: bug

#374 (MAINT) Ensure each job has a test matrix
  .github/workflows/ci.yml
Labels: maintenance

#375 (MAINT) Bump gem version
  lib/puppetlabs_spec_helper/version.rb
Labels: maintenance

#377 pathspec: Allow 1.x
  puppetlabs_spec_helper.gemspec
Labels: community

#378 puppet-lint: Allow 3.x
  puppetlabs_spec_helper.gemspec
Labels: community

#379 (CONT-515) Fix uninitialized constant error
  .rubocop.yml
  lib/puppetlabs_spec_helper/puppetlabs_spec/files.rb
  lib/puppetlabs_spec_helper/puppetlabs_spec/fixtures.rb
  lib/puppetlabs_spec_helper/puppetlabs_spec/puppet_internals.rb
  lib/puppetlabs_spec_helper/tasks/check_symlinks.rb
  lib/puppetlabs_spec_helper/tasks/fixtures.rb
Labels: bug

#380 (MAINT) Release prep for v5.0.2
  CHANGELOG.md
  lib/puppetlabs_spec_helper/version.rb
Labels: maintenance

#383 (MAINT) Release prep for v5.0.3
  CHANGELOG.md
  lib/puppetlabs_spec_helper/version.rb
Labels: maintenance
