Repository puppetlabs/puppetlabs_spec_helper, pull requests merged in 2023-04, with the labels that each got.

#390 (CONT-807) Add Ruby 3.2 support
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  README.md
  lib/puppetlabs_spec_helper/module_spec_helper.rb
  lib/puppetlabs_spec_helper/puppet_spec_helper.rb
  lib/puppetlabs_spec_helper/puppetlabs_spec/files.rb
  lib/puppetlabs_spec_helper/puppetlabs_spec/fixtures.rb
  lib/puppetlabs_spec_helper/rake_tasks.rb
  lib/puppetlabs_spec_helper/tasks/fixtures.rb
  puppetlabs_spec_helper.gemspec
  spec/spec_helper.rb
  spec/unit/puppetlabs_spec_helper/tasks/check_symlinks_spec.rb
  spec/unit/puppetlabs_spec_helper/tasks/fixture_helpers_spec.rb
  spec/watchr.rb
Labels: backwards-incompatible

#391 (CONT-807) Mapping RC dependencies
  puppetlabs_spec_helper.gemspec
Labels: maintenance

#393 (CONT-807) Ruby 3 / Puppet 8 Additions
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release_prep.yml
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  HISTORY.md
  lib/puppetlabs_spec_helper/module_spec_helper.rb
  lib/puppetlabs_spec_helper/rake_tasks.rb
  lib/puppetlabs_spec_helper/tasks/check_symlinks.rb
  spec/acceptance/smoke_spec.rb
  spec/spec_helper.rb
  spec/unit/puppetlabs_spec_helper/tasks/check_symlinks_spec.rb
  spec/unit/puppetlabs_spec_helper/tasks/check_test_file_spec.rb
  spec/unit/puppetlabs_spec_helper/tasks/fixture_helpers_spec.rb
  spec/watchr.rb
Labels: enhancement

#389 Use rspec-puppet settings to configure Puppet
  lib/puppetlabs_spec_helper/module_spec_helper.rb
Labels: enhancement, community

#395 (MAINT) Bump lint and rspec-puppet dependencies
  puppetlabs_spec_helper.gemspec
Labels: bug
