Repository puppetlabs/puppetlabs_spec_helper, pull requests merged in 2023-10, with the labels that each got.

#412 (bug) - remove obselete manfiest dir config setting & require rspec-puppet 4.x
  lib/puppetlabs_spec_helper/module_spec_helper.rb
  puppetlabs_spec_helper.gemspec
Labels: bugfix

#415 (CAT-1222) - Require puppetlabs-rspec-puppet over rspec-puppet
  puppetlabs_spec_helper.gemspec
Labels: feature

#411 (CAT-1256) Roll out new puppet-lint gem
  puppetlabs_spec_helper.gemspec
Labels: backwards-incompatible, hacktoberfest
