Repository puppetlabs/puppetlabs_spec_helper, pull requests merged in 2024-09, with the labels that each got.

#473 (CAT-1984) - Add forge auth to fixtures module install
  README.md
  lib/puppetlabs_spec_helper/tasks/fixtures.rb
  spec/unit/puppetlabs_spec_helper/tasks/fixture_helpers_spec.rb
Labels: feature

#472 (breaking) - Remove build rake tasks
  lib/puppetlabs_spec_helper/rake_tasks.rb
Labels: backwards-incompatible

#474 cleanup: remove class_parameter_defaults disable
  lib/puppetlabs_spec_helper/rake_tasks.rb
Labels: bugfix

#475 (maint) - Small readme fix
  README.md
Labels: maintenance
