Repository puppetlabs/puppetlabs_spec_helper, pull requests merged in 2024-06, with the labels that each got.

#454 Revert "spec_standalone: apply default formatting"
  lib/puppetlabs_spec_helper/rake_tasks.rb
Labels: bugfix

#460 (maint) Exclude breaking rubocop versions
  Gemfile
Labels: maintenance

#462 (maint) Update labeller.yml to pull_request
  .github/workflows/labeller.yml
Labels: maintenance

#459 Add Ruby 3.3 to CI matrix
  .github/workflows/ci.yml
Labels: community

#463 Revert "(maint) Update labeller.yml to pull_request"
  .github/workflows/labeller.yml
Labels: maintenance

#467 Revert "(maint) Exclude breaking rubocop versions"
  Gemfile
  lib/puppetlabs_spec_helper/puppetlabs_spec/puppet_internals.rb
  lib/puppetlabs_spec_helper/tasks/fixtures.rb
Labels: maintenance
