Repository puppetlabs/puppetlabs_spec_helper, pull requests merged in 2024-02, with the labels that each got.

#430 (GH-422) - Add Safe Navigation Operator to hash['ref']
  lib/puppetlabs_spec_helper/tasks/fixtures.rb
Labels: bugfix

#431 (GH-397) - Honour default symlink when additional symlinks delcared
  .rubocop_todo.yml
  lib/puppetlabs_spec_helper/tasks/fixtures.rb
Labels: bugfix

#433 puppet-syntax: Require 4.x
  puppetlabs_spec_helper.gemspec
Labels: community, bugfix

#432 dependabot: check for github actions and bundler
  .github/dependabot.yml
Labels: maintenance, community
